### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by pwalsh** [okfn/app-theme#1]
Hi @mintcanary 

Stuff breaks when compiling because this is commented: 

https://github.com/okfn/app-theme/blob/master/css/main.scss#L18

**Comment by smth** [comment]
I copied (and edited) the Bootstrap variables to here https://github.com/okfn/app-theme/blob/master/_sass/_base.scss

**Comment by pwalsh** [comment]
In that case, there are variables missing in what was copied over. If I leave the bootstrap/variables import commented, I get the following:

```
# run the sass compiler
 sass web/theme/static/css/app.scss web/theme/static/css/app.css
```

errors:

```
Error: Undefined variable: "$form-group-margin-bottom".
        on line 207 of bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_forms.scss
        from line 26 of web/theme/static/css/app.scss
```

and then I suppress that error by commenting line 26 in my source:

```
Error: Undefined mixin 'form-inline'.
        on line 296 of bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_navbar.scss, in `form-inline'
        from line 296 of bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_navbar.scss
        from line 35 of web/theme/static/css/app.scss
```

If you see I missed something when I copied your theme in, please let me know. here is my version of your original main.scss:

https://github.com/okfn/goodtables-web/blob/feature/reskin/web/theme/static/css/app.scss

**Comment by smth** [comment]
Hmm I don't think there is anything missing in the base file http://www.diffnow.com/?report=eukmp

The biggest difference I can think of is its location in the file structure..

**Comment by pwalsh** [comment]
@mintcanary for whatever reason, your _variables file from bower is not the same as mine, nor the one in the bootstrap-sass repo. Note here is the (first) missing variable I encountered:

https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L216

**Comment by smth** [comment]
Won't fix, deprecated. https://github.com/okfn/app-theme/tree/gh-pages/css/sass
