### ISSUE TITLE
Suggestions for app-specific code

### ISSUE THREAD

**Issue by pwalsh** [okfn/app-theme#2]
@mintcanary 

This file: https://github.com/okfn/app-theme/blob/master/_sass/_app.scss

Currently has code for two projects: good tables and spend publishing dashboard.

I've got two suggestions:
1. Rename this to "custom", which matches the way it is called in the main css file via comments
2. Have a separate file per app (seeing as this theme is probably going to be developed further)

Example:

```
custom-goodtables.scss

custom-spendpublishingdashboard.scss
```

**Comment by smth** [comment]
On point 2:
I was thinking people would just delete everything in this file, and replace with styles for whatever project they are creating (unless of course you happening to be creating one of those two example apps, in which case you could just delete the one you aren't using). Admittedly, having two examples is confusing (but was part of the brief). In the long term, thinking about this as a generic theme, this file should probably be empty.

**Comment by pwalsh** [comment]
this is solved now. Thanks @mintcanary
