### ISSUE TITLE
Ribbon is old one now new one

### ISSUE THREAD

**Issue by rufuspollock** [okfn/app-theme#5]
@mintcanary theme still seems to have old ribbon rather than the new one. Is that intentional?

**Comment by smth** [comment]
Only in so much as I was waiting for your approval on the new one. I'll take this as sign-off.

**Comment by smth** [comment]
Fixed https://github.com/okfn/app-theme/commit/33740ca9e966759c37f476fa823e3bcd8ad69b6a
