### ISSUE TITLE
think about the "green"

### ISSUE THREAD

**Issue by rufuspollock** [okfn/app-theme#9]
Really not sure about the default green - i know it is sort of "OK" style but not to late to change.

What other colours could we trial (e.g. we had yellow on open data index).

@mintcanary wdyt?

**Comment by smth** [comment]
I'm not sure if you are suggesting globally changing the green (across Open Knowledge), or not using the green for this theme.

If it's the former, I don't think it's a secret that I'm not a fan of this green. I suggested it be [tweaked](https://cloud.githubusercontent.com/assets/1375708/8326697/c353a222-1a5a-11e5-82d8-c0939d1f173e.jpg) at the time it was presented. So if that's the case, I'd be cautious but on board.

If the latter, it seems to me that would undermine the purpose of this theme (to provide Open Knowledge branding?). So while we could replace the green with yellow, or any other colour, I'm not sure what that would leave us with, and of what value it would be. I guess I'm arguing here that Open Data Index is not "on brand". It at least doesn't follow the [example](https://cloud.githubusercontent.com/assets/1375708/8327146/14e31174-1a5e-11e5-8bc3-93a01aa37538.jpg) given explicitly in the guidelines. In my view, the Open Data Index is not branded as Open Knowledge, but, much like most of our "sub-brands" has it's own identity (of which the yellow is a part).

Whether it's revisiting our branding, or deciding how sub-brands should be treated, I think this question has deep and far reaching implications. So I'm hesitant to just pick a colour out of the air. Our guidelines do include a couple of secondary accent colours, but again, I'm not convinced these would sufficiently evoke the Open Knowledge brand (and to be frank, they are equally garish).

**Comment by smth** [comment]
Doing it https://github.com/okfn/foundation/issues/259.
